# Use the official Nginx image
FROM nginx:alpine

# Copy static files from your project folder to the container
COPY . /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Nginx will start automatically



# # Build the Docker image
# docker build -t my-web-app .

# # Run the Docker container
# docker run -d -p 8080:80 my-web-app