version: '3.8'

services:
  route_tracker_streamlit_app:
    image:  ghcr.io/jalcocert/py_routetracker:v1.0 
    container_name: py_routetracker
    ports:
      - "8509:8501"
    working_dir: /app
    command: streamlit run app.py
    #command: python3 app.py
    #command: tail -f /dev/null #keep it running