 # This workflow will install build and push the container of the Py_Route_Tracker app of this repository.

name: CI/CD Pipeline

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CICD_PyRouteTracker_Token }} #Settings -> Dev Settings -> PAT's -> Tokens +++ Repo Settings -> Secrets & variables -> Actions -> New repo secret 

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: . #./Z_Deploy_me  #. # Specify the path to your Dockerfile and source code
        push: true
        tags: |
          ghcr.io/jalcocert/py_routetracker:v1.0
          ghcr.io/jalcocert/py_routetracker:latest
        
        #tags: ghcr.io/jalcocert/py_routetracker:v1.0
        #tags: ghcr.io/jalcocert/py_routetracker:${{ github.sha }}